### PR TITLE
add blog link

### PR DESCRIPTION
**Pull request by SathyaBhat**

### CODE REVIEW

**Review by dA505819 — APPROVED** [review]
It will enhance the website!

**Review by yash982000 — COMMENTED** [review]
Looks Awesome Idea to me.
Just a quick doubt. Do we have to remove the sponsor section?
Also, if we can keep the Blog section after Speakers, won't it be more apt?

**Comment by SathyaBhat** [comment]
We never had sponsors (and you can see is commented out)

**Comment by yash982000** [comment]
> We never had sponsors (and you can see is commented out)

Okay, thanks for pointing out.

**Comment by SathyaBhat** [comment]
> Also, if we can keep the Blog section after Speakers, won't it be more apt?

@yash982000 this is done 

https://deploy-preview-26--communityday-india.netlify.app/

**Comment by yash982000** [comment]
> > Also, if we can keep the Blog section after Speakers, won't it be more apt?
> 
> @yash982000 this is done
> 
> https://deploy-preview-26--communityday-india.netlify.app/

Okay, great. Let me know if any more changes to be done.

**Pull request merged**
